# Add account settings and API keys here
# this file should be listed in .gitignore to keep settings secret
# each entry gets set as a local environment variable. 
# this file overrides ENV variables in the Unix shell
For example, setting:
# GMAIL_USERNAMEL 'Your_Gmail_Username'
# makes 'Your_Gmail_Username' available as ENV['GMAIL_USERNAME']
GMAIL_USERNAME: 'doneil1580@gmail.com'
GMAIL_PASSWORD: 'Patrick99$'
# needs to be a gmail account if using smtp